export const SET_CONFIGS = "SET_CONFIGS";
export const RESET_CONFIG = "RESET_CONFIG";

export const SET_TEMP_STATE = "SET_TEMP_STATE";
export const SET_TEMP_STATE_REQUEST = "SET_TEMP_STATE_REQUEST";
export const REMOVE_TEMP_STATE_REQUEST = "REMOVE_TEMP_STATE_REQUEST";

export const SET_REQUEST = "SET_REQUEST"
export const REMOVE_REQUEST = "REMOVE_REQUEST"
export const SET_REQUESTS = "SET_REQUESTS"
export const CLEAR_REQUEST = "CLEAR_REQUEST"

export const FETCHING_REQUEST = 'FETCHING_REQUEST';
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS';
export const FETCHING_FAILUR = 'FETCHING_FAILUR';
